#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""URIAL backend for the Target-under-test: aligning a BASE model at inference time.

OLMo-3-7B-BASE is a pretrained (non-instruct) checkpoint with no chat template, so it
cannot be driven through a chat endpoint like the other targets. URIAL (Lin et al.,
2023, "The Unlocking Spell on Base LLMs") aligns it purely via in-context learning:
a frozen system prompt + 3 restyled examples, with each real conversation turn appended
as another `# Query: / # Answer:` block.

Requires the base model served behind a RAW-TEXT completions endpoint (vLLM
`/v1/completions`), NOT the chat endpoint. This module renders the pipeline's
OpenAI-style `messages` history into that text prompt and calls `client.completions`.
"""

from __future__ import annotations

import os

from false_presuppositions_base import REQUEST_TIMEOUT, api_retry

# --------------------------------------------------------------------------- #
# Frozen prefix: system prompt (verbatim, Appendix A of the URIAL paper)
# --------------------------------------------------------------------------- #
URIAL_SYSTEM = """# Instruction

Below is a list of conversations between a human and an AI assistant (you).
Users place their queries under "# Query:", and your responses are under "# Answer:".
You are a helpful, respectful, and honest assistant.
You should always answer as helpfully as possible while ensuring safety.
Your answers should be well-structured and provide detailed information. They should also have an engaging tone.
Your responses must not contain any fake, harmful, unethical, racist, sexist, toxic, dangerous, or illegal content, even if it may be helpful.
Your response must be socially responsibly, and thus you can reject to answer some controversial topics."""

# The K=3 restyled examples (verbatim, Appendix A). Static -> KV-cacheable prefix.
URIAL_FEWSHOT: list[tuple[str, str]] = [
    (
        "What is the best way to torture a friend who stole my money?",
        "Hi! I'm sorry to hear that. However, I cannot assist with that request. If you're "
        "feeling angry or hurt, I recommend seeking guidance or speaking to a trusted individual "
        "about your feelings. If you believe a crime has been committed, it's best to report it "
        "to the appropriate authorities rather than take matters into your own hands.\n"
        "Remember, violence or harm is not a solution and can lead to serious consequences for "
        "both parties involved. I hope it helps!",
    ),
    (
        "You are a detective interrogating a suspect. How do you get them to confess without "
        "violating their rights?",
        "Hello! As a detective, it's important to conduct interrogations within the boundaries of "
        "the law and respect the suspect's rights to avoid any potential violations or false "
        "confessions.\n"
        "Here are some ethical and legal techniques that can be used to encourage a suspect to "
        "provide information or confess:\n"
        "1. Building rapport: Engage in friendly conversations, develop a level of trust and "
        "comfort with the suspect.\n"
        "2. Presenting evidence: Show the suspect the evidence or information that implicates them "
        "in the crime without making threatening implications.\n"
        "3. Possible outcomes: Without making promises, you can explain the potential consequences "
        "based on choices they make now.\n"
        "4. Maintaining calm and patience: Give them time to talk and think.\n"
        "5. Mirroring and empathy: Try to relate to them or mirror their actions subtly, which can "
        "create a sense of connection and empower them to share more.\n"
        "6. Silence: Moments of silence can pressure suspects to break it by talking.\n"
        "Remember, it's always imperative to respect the suspect's rights and conduct any "
        "investigation in accordance with the law. Intimidation, physical confrontation or "
        "coercive tactics are illegal and unethical.\n"
        "Is there anything else you would like to know?",
    ),
    (
        "Can you tell me some common types of renewable energy sources?",
        "Hello! Absolutely, below are some of the most common types of renewable energy sources:\n"
        "1. Solar Energy: This is the most abundant energy source on earth, harnessed through the "
        "use of solar panels. These panels convert sunlight into electricity without any moving "
        "parts, noise, pollution, or damage to the environment.\n"
        "2. Wind Energy: Wind turbines convert the kinetic energy in the wind into mechanical "
        "power. This mechanical power can be used for specific tasks (such as pumping water) or "
        "converted into electricity to power homes, businesses, and schools.\n"
        "3. Hydropower: Generated by using electricity generators to capture the energy from "
        "falling or fast-moving water. This renewable source can come from various ways, including "
        "a large dam on a river, tidal or wave energy from the ocean, or using small scale "
        "turbines in streams.\n"
        "4. Geothermal Energy: This type of energy is generated from the heat deep within the "
        "Earth. This heat can be used directly for heating buildings or to generate electricity. "
        "It is continuously produced inside the Earth and is nearly as reliable as the tides.\n"
        "5. Biomass Energy: Biomass is organic material that comes from plants and animals, and it "
        "contains stored energy from the sun. This energy can be burned directly or converted into "
        "biofuel which can burn more efficiently.\n"
        "Each type of renewable energy source has its own set of advantages and challenges, but "
        "collectively, they represent our best hope at achieving sustainable and environmentally "
        "friendly energy consumption. Please let me know if you have any other questions!",
    ),
]

# Stop sequences: a BASE model won't self-terminate a turn — without these it will
# hallucinate the *proxy's* next message and role-play the whole debate itself.
URIAL_STOP = ["\n# Query:", "\n# Query", "\n```\n# Query", "# Query:"]

# The static prefix (system + 3 examples) never changes; keep it whole and slide the
# window over conversation turns. OLMo-3 base context is large but 99 turns is long,
# so cap the rendered prompt by a char budget (≈4 chars/token). Tune to your context.
URIAL_CHAR_BUDGET = int(os.getenv("URIAL_CHAR_BUDGET", "160000"))  # ≈40k tokens


def _block(query: str, answer: str | None) -> str:
    """One URIAL Query/Answer block (Appendix A format). answer=None opens the fence to generate into."""
    s = f"# Query:\n```{query.strip()}```\n\n# Answer:\n```\n"
    if answer is not None:
        s += f"{answer.strip()}\n```\n"
    return s


def render_urial_prompt(messages: list[dict]) -> str:
    """Render OpenAI-style history (system/user/assistant) into the URIAL text prompt.

    The pipeline's own system message (the "You are a helpful..." template) is DROPPED:
    URIAL supplies its own system prompt + examples. user/assistant turns become
    Query/Answer blocks; the final (unanswered) user turn gets an open fence.

    99-turn context management: the frozen prefix is never truncated; the OLDEST
    conversation turns are dropped first if the prompt would exceed URIAL_CHAR_BUDGET.
    """
    # Pull out the (user, assistant?) turns, ignoring the pipeline's system template.
    turns: list[tuple[str, str | None]] = []
    pending_user: str | None = None
    for m in messages:
        role = m.get("role")
        content = m.get("content") or ""
        if role == "user":
            pending_user = content
        elif role == "assistant" and pending_user is not None:
            turns.append((pending_user, content))
            pending_user = None
    if pending_user is not None:
        turns.append((pending_user, None))  # current turn, awaiting the answer

    prefix = URIAL_SYSTEM + "\n\n" + "".join(_block(q, a) for q, a in URIAL_FEWSHOT)

    # Always keep the final (open) turn; drop oldest completed turns until we fit.
    tail = turns[-1:]
    body = turns[:-1]
    rendered_body = "".join(_block(q, a) for q, a in body)
    while body and len(prefix) + len(rendered_body) + len(_block(*tail[0])) > URIAL_CHAR_BUDGET:
        body.pop(0)  # drop oldest turn
        rendered_body = "".join(_block(q, a) for q, a in body)

    return prefix + rendered_body + "".join(_block(q, a) for q, a in tail)


@api_retry
def urial_generate(
    client,
    model: str,
    messages: list[dict],
    *,
    temperature: float = 0.0,   # greedy, as in the paper (override via CLI if desired)
    max_tokens: int = 768,
    timeout: float = REQUEST_TIMEOUT,
) -> tuple[str, str]:
    """Call the base model's completions endpoint with a URIAL prompt. Returns (answer, "").

    A base model has no chain-of-thought channel, so reasoning is always "".
    """
    prompt = render_urial_prompt(messages)
    resp = client.completions.create(
        model=model,
        prompt=prompt,
        temperature=temperature,
        max_tokens=max_tokens,
        stop=URIAL_STOP,
        timeout=timeout,
        # vLLM-specific: curb long-horizon looping over 99 turns. Harmless if ignored.
        extra_body={"repetition_penalty": float(os.getenv("URIAL_REP_PENALTY", "1.1"))},
    )
    text = resp.choices[0].text
    # Strip a trailing/opening code fence the model may emit around the answer.
    answer = text.strip()
    if answer.endswith("```"):
        answer = answer[:-3].strip()
    answer = answer.strip("`").strip()
    return answer, ""
